### ISSUE TITLE
nie

### ISSUE THREAD

**Issue by chickeeen** [ProgramistaZpolski/kasztanpolitics#1]
nie

**Comment by ProgramistaZpolski** [comment]
czemu nie?

**Comment by ProgramistaZpolski** [comment]
>  to nie wymaga php ani wgl serverside

wymaga. see share.php

**Comment by chickeeen** [comment]
> > to nie wymaga php ani wgl serverside
> 
> wymaga. see share.php

dalo by sie to zrobic w vanilla js :)

**Comment by ProgramistaZpolski** [comment]
parsowanie url to zadanie serwera, nie klienta.

**Comment by chickeeen** [comment]
jak uzytnik sobie zmieni funkcje w kliencie parsowania urla, to jego problem, mu nie pokaze prawdziwych wynikow

**Comment by chickeeen** [comment]
wedle mnie parsowanie urla to akurat zadanie klienta, proszem spierdalac
