### ISSUE TITLE
nie

### ISSUE THREAD

**Issue by TheVision6212** [ProgramistaZpolski/kasztanpolitics#2]
proszę się odczepić od kasztan corp

**Comment by ProgramistaZpolski** [comment]
Ale ja nie mam nic do kasztan corp

**Comment by TheVision6212** [comment]
robisz to specjalnie, żeby nas wkurzyć

**Comment by ProgramistaZpolski** [comment]
nie robię tego specjalnie, robię tego forka żeby kontynuować kasztanpolitics

**Comment by TheVision6212** [comment]
to proszę sobie to zrebrandować na pzplpolitics i do widzenia

**Comment by chickeeen** [comment]
> nie robię tego specjalnie, robię tego forka żeby kontynuować kasztanpolitics

ja je bede kontynuował, ale pierw wypierdole pornhubp
